### PR TITLE
One last commit :)

### PR DESCRIPTION
**Pull request by chitrangpatel**
To  allow imports from transforms, we had to add an __init__.py file inside transforms directory.

### CODE REVIEW

**Comment by mrafieir** [comment]
@chitrangpatel We already import transforms in `ch_frb_rfi/__init__.py`. So an **empty** `ch_frb_rfi/transforms/__init__.py` would suffice I suppose?

**Comment by chitrangpatel** [comment]
I can test it. Wait.

**Comment by chitrangpatel** [comment]
Yep. That works too.

**Comment by mrafieir** [comment]
Great. I suggest that we remove the content of `ch_frb_rfi/transforms/__init__.py`.

**Pull request merged**
