### PR TITLE
Found a bug while testing with the rest of the pipeline (L1 to L4). 

### PR DESCRIPTION
**Pull request by chitrangpatel**
Need this function to run the pipeline in a custom directory. ie. Not in /data

### CODE REVIEW

**Comment by mrafieir** [comment]
A duplicate (`run_in_scratch_dir`) existed in v7. I combined the two functionalities by adding an extra kwarg to `run_in_scratch_dir` (backward compatible). Please add any extra features, if really needed by `run_in_custom_dir`, to the original function.

**Comment by chitrangpatel** [comment]
Should I just add a boolean kwarg in `run_in_scratch_dir` to make it run in
custom directories?

**Comment by mrafieir** [comment]
`run_in_scratch_dir` has such kwarg in v8. You just have to set `dirname` to a `str`. Have you tried running your script(s) with it?

**Comment by chitrangpatel** [comment]
Yeah I did. It works. Should have tried that earlier.
No need to pull this in. Thanks!

**Comment by mrafieir** [comment]
Great!

**Pull request closed without merging**
